"use client";
import { useCallback,useMemo,useRef,useState } from "react";
import { Network,X } from "lucide-react";
import { useDashboardFilters } from "@/components/DashboardFilterProvider";
import { useAccessibleModal } from "@/components/ui/useAccessibleModal";
import { getRegionById,regions } from "@/lib/data-foundation";
import { buildCollaborationNetwork,collaborationActivitySources,collaborationDomainOptions,institution,institutions,layoutCollaborationNetwork,selectCollaborations,type CollaborationActivity } from "@/lib/collaboration-data";
import { monitoringDomainLabels,validateCollaborationRelatedRecords } from "@/lib/monitoring-record-resolver";
import { paginate,stableSort } from "@/lib/monitoring-table";
import { formatMonitoringDate,formatMonitoringPercent,formatMonitoringSeason,formatMonitoringStatus,formatMonitoringTimestamp } from "@/lib/monitoring-presentation";
type SortKey="title"|"domain"|"progress"|"due";const PAGE_SIZE=2;
const badge=(value:string)=><span className={`status-badge status-${value.toLowerCase().replace(/[^a-z]+/g,"-")}`}>{formatMonitoringStatus(value)}</span>;
function Detail({item,onClose,fallbackRef}:{item:CollaborationActivity;onClose:()=>void;fallbackRef:React.RefObject<HTMLElement|null>}){
 const ref=useRef<HTMLDivElement>(null);useAccessibleModal(onClose,ref,fallbackRef);const resolution=validateCollaborationRelatedRecords(item);
 return <div className="monitoring-modal-overlay" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section ref={ref} className="monitoring-modal monitoring-detail-modal" role="dialog" aria-modal="true" aria-labelledby="collab-title" tabIndex={-1}><header><div><span>Kolaborasi OPD</span><h2 id="collab-title">{item.title}</h2><p>{badge(item.status)} <strong>{item.progress_percent}%</strong></p></div><button onClick={onClose} aria-label={`Tutup detail ${item.title}`}><X aria-hidden="true"/></button></header><div className="monitoring-modal-body detail-sections">
 <section><h3>Identitas dan konteks</h3><dl>{[["ID kegiatan",item.id],["Judul kegiatan",item.title],["Domain",item.domain],["Musim",formatMonitoringSeason(item.season_id)],["Wilayah",getRegionById(item.region_id)?.name??"Kabupaten Merauke"]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>
 <section><h3>Pelaksana</h3><dl><div><dt>Koordinator</dt><dd>{institution(item.coordinator_institution_id)?.name??"Belum tersedia"}</dd></div><div><dt>Peserta</dt><dd>{item.participant_institution_ids.map(id=>institution(id)?.name).join(", ")||"Belum tersedia"}</dd></div></dl></section>
 <section><h3>Jadwal</h3><dl>{[["Tanggal mulai",formatMonitoringDate(item.start_date)],["Tenggat",formatMonitoringDate(item.due_date)],["Tanggal selesai",item.completed_at?formatMonitoringDate(item.completed_at):"Belum selesai"]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>
 <section><h3>Prioritas dan tindak lanjut</h3><dl><div><dt>Prioritas</dt><dd>{badge(item.priority)}</dd></div><div><dt>Tindak lanjut</dt><dd>{item.next_action??"Belum tersedia"}</dd></div></dl></section>
 <section className="related-records"><h3>Related records</h3><p><b>Status resolusi:</b> {resolution.valid?`${resolution.resolvedCount} dari ${resolution.totalCount} referensi berhasil diverifikasi.`:"Referensi data tidak valid."}</p>{resolution.items.map(({reference,record},index)=><article key={reference?`${reference.domain}:${reference.record_id}`:`invalid-${index}`}><strong>{reference?monitoringDomainLabels[reference.domain]:"Referensi tidak valid"}</strong><span>{record?.label??"Record tidak ditemukan"}</span><small>{record?`${record.regionLabel} · ${formatMonitoringSeason(record.season_id)} · ${formatMonitoringStatus(record.monitoring_status)} · ${formatMonitoringStatus(record.validation_status)}`:"Referensi data tidak valid"}</small></article>)}</section>
 <section><h3>Metadata monitoring</h3><dl>{[["Status monitoring",formatMonitoringStatus(item.monitoring_status)],["Validasi",formatMonitoringStatus(item.validation_status)],["Sumber/instansi",collaborationActivitySources([item])],["Tipe sumber",formatMonitoringStatus(item.source_type)],["Tipe data",formatMonitoringStatus(item.data_type)],["Diperbarui",formatMonitoringTimestamp(item.updated_at)]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section><p className="simulation-disclaimer">Data koordinasi bersifat simulasi prototipe dan bukan aplikasi disposisi resmi.</p>
 </div><footer><button onClick={onClose}>Tutup</button></footer></section></div>;
}
function NetworkView({activities}:{activities:readonly CollaborationActivity[]}){
 const[active,setActive]=useState<string|null>(null),network=buildCollaborationNetwork(activities),nodes=layoutCollaborationNetwork(network.nodes,800,420),positions=new Map(nodes.map(node=>[node.id,node]));
 if(!network.edges.length)return <section className="monitoring-card collaboration-network"><h2>Jejaring Kolaborasi</h2><div className="network-empty"><p className="table-empty">Belum ada hubungan kegiatan pada konteks terpilih.</p></div></section>;
 return <section className="monitoring-card collaboration-network"><div className="network-heading"><h2>Jejaring Kolaborasi</h2><p><b>N hubungan</b> menunjukkan jumlah kegiatan bersama antarinstansi.</p></div><div className="network-scroll"><svg className="network-canvas" viewBox="0 0 800 420" role="img" aria-labelledby="network-summary"><title id="network-summary">{network.accessibleSummary}</title><g className="network-edges">{network.edges.map(edge=>{const a=positions.get(edge.sourceInstitutionId),b=positions.get(edge.targetInstitutionId),related=active===edge.sourceInstitutionId||active===edge.targetInstitutionId;return a&&b?<line key={edge.id} className={active?(related?"is-active":"is-dimmed"):undefined} x1={a.x} y1={a.y} x2={b.x} y2={b.y}><title>{institution(edge.sourceInstitutionId)?.name} ke {institution(edge.targetInstitutionId)?.name}, {edge.activityCount} kegiatan</title></line>:null})}</g><g>{nodes.map(node=><g key={node.id} className={`network-svg-node${active===node.id?" is-active":active?" is-dimmed":""}${node.label.includes("Sekretariat")?" is-primary":""}`} transform={`translate(${node.x} ${node.y})`} tabIndex={0} role="group" aria-label={`${node.label}, ${node.activityCount} hubungan kegiatan`} onMouseEnter={()=>setActive(node.id)} onMouseLeave={()=>setActive(null)} onFocus={()=>setActive(node.id)} onBlur={()=>setActive(null)}><rect x="-64" y="-30" width="128" height="60" rx="11"/><text textAnchor="middle" y="-4">{node.label}</text><text className="network-count" textAnchor="middle" y="16">{node.activityCount} hubungan</text></g>)}</g></svg></div><ul className="network-mobile-list">{network.edges.map(edge=><li key={edge.id}><b>{institution(edge.sourceInstitutionId)?.name} → {institution(edge.targetInstitutionId)?.name}</b><span>{edge.activityCount} kegiatan · {edge.domains.join(", ")}</span></li>)}</ul><p className="sr-only">{network.accessibleSummary}</p></section>;
}
export default function CollaborationPage(){
 const{filters,setSeason,setDistrict}=useDashboardFilters();const headingRef=useRef<HTMLHeadingElement>(null);const[agency,setAgency]=useState("all"),[domain,setDomain]=useState("all"),[status,setStatus]=useState("all"),[priority,setPriority]=useState("all"),[validation,setValidation]=useState("all"),[query,setQuery]=useState(""),[sort,setSort]=useState<SortKey>("due"),[asc,setAsc]=useState(true),[page,setPage]=useState(1),[detail,setDetail]=useState<{item:CollaborationActivity;context:string}|null>(null);const close=useCallback(()=>setDetail(null),[]),contextKey=[filters.seasonId,filters.regencyId,filters.districtId,filters.villageId].join(":");
 const selected=useMemo(()=>selectCollaborations(filters.seasonId,filters.districtId??"93.01"),[filters.seasonId,filters.districtId]);
 const filtered=useMemo(()=>selected.items.filter(item=>(agency==="all"||item.coordinator_institution_id===agency||item.participant_institution_ids.includes(agency))&&(domain==="all"||item.domain===domain)&&(status==="all"||item.status===status)&&(priority==="all"||item.priority===priority)&&(validation==="all"||item.validation_status===validation)&&item.title.toLowerCase().includes(query.toLowerCase())),[selected.items,agency,domain,status,priority,validation,query]);
 const items=useMemo(()=>stableSort(filtered,item=>sort==="title"?item.title:sort==="domain"?item.domain:sort==="progress"?item.progress_percent:item.due_date,asc?"asc":"desc"),[filtered,sort,asc]);
 const visibleDetail=detail?.context===contextKey&&items.some(item=>item.id===detail.item.id)?detail.item:null,pagination=paginate(items,page,PAGE_SIZE),local=(setter:(value:string)=>void)=>(value:string)=>{setter(value);setPage(1);close()},sortBy=(key:SortKey)=>{setAsc(sort===key?!asc:true);setSort(key);setPage(1)},districts=regions.filter(item=>item.parent_id==="93.01"&&item.administrative_type==="district"),aggregate=selected.aggregate;
 return <div className="monitoring-page collaboration-page"><div className="monitoring-heading"><span className="monitoring-heading-icon"><Network aria-hidden="true"/></span><div><span>SIMULASI PROTOTIPE · PEMERINTAH PROVINSI PAPUA SELATAN</span><h1 ref={headingRef} tabIndex={-1}>KOLABORASI OPD &amp; INSTANSI</h1><p>Koordinasi Program dan Tindak Lanjut Ketahanan Pangan</p></div></div><p className="simulation-disclaimer">Halaman ini bukan aplikasi disposisi resmi dan bukan pengganti sistem administrasi pemerintahan.</p>
 <section className="monitoring-filters" aria-label="Filter Kolaborasi OPD"><label>Musim<select value={filters.seasonId} onChange={e=>{close();setPage(1);setSeason(e.target.value)}}><option value="MT1-2026">MT I 2026</option><option value="MT2-2026">MT II 2026</option></select></label><label>Distrik<select value={filters.districtId??""} onChange={e=>{close();setPage(1);setDistrict(e.target.value||null)}}><option value="">Kabupaten Merauke</option>{districts.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{[["OPD/Instansi",agency,setAgency,institutions.map(item=>[item.id,item.name])],["Domain",domain,setDomain,collaborationDomainOptions.map(item=>[item,item])],["Status",status,setStatus,["Direncanakan","Berjalan","Selesai","Tertunda"].map(item=>[item,item])],["Prioritas",priority,setPriority,["Rendah","Sedang","Tinggi","Kritis"].map(item=>[item,item])],["Validasi",validation,setValidation,[["approved",formatMonitoringStatus("approved")],["pending",formatMonitoringStatus("pending")]]]].map(([labelText,value,setter,options])=><label key={labelText as string}>{labelText as string}<select value={value as string} onChange={e=>local(setter as (value:string)=>void)(e.target.value)}><option value="all">Semua</option>{(options as string[][]).map(([option,label])=><option value={option} key={option}>{label}</option>)}</select></label>)}<label className="monitoring-search-field">Pencarian<input className="monitoring-search" value={query} onChange={e=>local(setQuery)(e.target.value)} placeholder="Cari program atau kegiatan" aria-label="Cari program kolaborasi"/></label></section>
 {!selected.monitored?<section className="compact-empty-state" role="status"><div><h2>Wilayah belum dipantau</h2><p>Data kolaborasi untuk Distrik {getRegionById(filters.districtId??"")?.name} belum tersedia pada cakupan prototipe.</p><small>Pilih wilayah terpantau untuk melihat program dan hubungan antarinstansi.</small></div></section>:selected.items.length===0?<section className="compact-empty-state" role="status"><div><h2>Belum ada kegiatan kolaborasi</h2><p>Wilayah ini telah dipantau, tetapi belum mempunyai kegiatan pada musim terpilih.</p></div></section>:<><section className="monitoring-kpis">{[["Instansi terlibat",aggregate.involvedInstitutionCount],["Program aktif",aggregate.activeProgramCount],["Program selesai",aggregate.completedProgramCount],["Rata-rata progres",formatMonitoringPercent(aggregate.averageProgress)],["Prioritas tinggi/kritis",aggregate.highCriticalPriorityCount],["Validasi",formatMonitoringPercent(aggregate.validationPercent)]].map(([labelText,value])=><article key={labelText}><span>{labelText}</span><strong>{value}</strong></article>)}</section><NetworkView activities={items}/>
 <section className="monitoring-card monitoring-table collaboration-table"><h2>Program dan Tindak Lanjut</h2><div className="table-scroll"><table><thead><tr>{[["title","Program/Kegiatan"],["domain","Domain"]].map(([key,labelText])=><th key={key} aria-sort={sort===key?(asc?"ascending":"descending"):"none"}><button className="table-sort" onClick={()=>sortBy(key as SortKey)}>{labelText}<span aria-hidden="true">{sort===key?(asc?"↑":"↓"):"↕"}</span></button></th>)}<th>Wilayah</th><th>Koordinator</th><th>Prioritas</th><th aria-sort={sort==="progress"?(asc?"ascending":"descending"):"none"}><button className="table-sort" onClick={()=>sortBy("progress")}>Progres<span aria-hidden="true">{sort==="progress"?(asc?"↑":"↓"):"↕"}</span></button></th><th aria-sort={sort==="due"?(asc?"ascending":"descending"):"none"}><button className="table-sort" onClick={()=>sortBy("due")}>Tenggat<span aria-hidden="true">{sort==="due"?(asc?"↑":"↓"):"↕"}</span></button></th><th>Status</th><th>Detail</th></tr></thead><tbody>{pagination.items.map(item=><tr key={item.id}><td>{item.title}</td><td>{item.domain}</td><td>{getRegionById(item.region_id)?.name??"Kabupaten Merauke"}</td><td>{institution(item.coordinator_institution_id)?.name}</td><td>{badge(item.priority)}</td><td><span className="progress-value">{item.progress_percent}%</span></td><td>{formatMonitoringDate(item.due_date,{short:true})}</td><td>{badge(item.status)}</td><td><button onClick={()=>setDetail({item,context:contextKey})} aria-label={`Buka detail ${item.title}`}>Detail</button></td></tr>)}</tbody></table>{!items.length&&<p className="table-empty">Tidak ada data sesuai filter.</p>}</div>{items.length>0&&<div className="table-pagination"><span>Menampilkan {(pagination.page-1)*PAGE_SIZE+1}–{Math.min(pagination.page*PAGE_SIZE,items.length)} dari {items.length}</span><div><button disabled={!pagination.hasPrevious} aria-label="Halaman kolaborasi sebelumnya" onClick={()=>setPage(value=>value-1)}>Sebelumnya</button>{Array.from({length:pagination.pageCount},(_,index)=><button key={index} aria-current={pagination.page===index+1?"page":undefined} onClick={()=>setPage(index+1)}>{index+1}</button>)}<button disabled={!pagination.hasNext} aria-label="Halaman kolaborasi berikutnya" onClick={()=>setPage(value=>value+1)}>Berikutnya</button></div></div>}</section></>}{visibleDetail&&<Detail item={visibleDetail} onClose={close} fallbackRef={headingRef}/>}</div>;
}
