export type YearOverYearDirection = "increase" | "decrease" | "unchanged" | "unavailable";
export type YearOverYearIndicatorId = "planting_area" | "harvested_area" | "gkg_production" | "productivity";
export type YearOverYearSource = { reference: string; methodology: string; monitoring_status: string };
export type YearOverYearComparison = { indicator_id:YearOverYearIndicatorId;active_value:number|null;comparison_value:number|null;comparison_year:number|null;active_season_id:string;comparison_season_id:string|null;region_id:string;active_period:string|null;comparison_period:string|null;percentage_change:number|null;direction:YearOverYearDirection;unavailable_reason:string|null;source:YearOverYearSource|null };
export type ComparisonInput=Omit<YearOverYearComparison,"percentage_change"|"direction"|"unavailable_reason">&{monitored:boolean};
const unavailable=(input:ComparisonInput,reason:string):YearOverYearComparison=>({...input,percentage_change:null,direction:"unavailable",unavailable_reason:reason});
export function buildYearOverYearComparison(input:ComparisonInput):YearOverYearComparison{if(!input.monitored)return unavailable(input,"Wilayah belum dipantau");if(typeof input.active_value!=="number"||!Number.isFinite(input.active_value))return unavailable(input,"Nilai aktif belum tersedia");if(typeof input.comparison_value!=="number"||!Number.isFinite(input.comparison_value))return unavailable(input,"Pembanding 2025 belum tersedia");if(input.comparison_value===0)return unavailable(input,"Nilai pembanding nol");if(!input.comparison_year||!input.comparison_season_id||!input.comparison_period||!input.source)return unavailable(input,"Metadata pembanding belum lengkap");const percentage_change=(input.active_value-input.comparison_value)/input.comparison_value*100;return{...input,percentage_change,direction:percentage_change>0?"increase":percentage_change<0?"decrease":"unchanged",unavailable_reason:null}}
// Registry produksi belum memiliki record indikator 2025 dengan wilayah, musim,
// cut-off, metodologi, status monitoring, dan sumber yang setara dengan data 2026.
export function selectExecutiveYearOverYearComparisons({seasonId,regionId,period,monitored,values}:{seasonId:string;regionId:string;period:string|null;monitored:boolean;values:Record<YearOverYearIndicatorId,number|null>}){return(Object.keys(values)as YearOverYearIndicatorId[]).map(indicator_id=>buildYearOverYearComparison({indicator_id,active_value:values[indicator_id],comparison_value:null,comparison_year:null,active_season_id:seasonId,comparison_season_id:null,region_id:regionId,active_period:period,comparison_period:null,source:null,monitored}))}
export function formatYearOverYearComparison(model:YearOverYearComparison){if(model.direction==="unavailable")return model.unavailable_reason==="Wilayah belum dipantau"?"Belum dipantau":"Pembanding 2025 belum tersedia";const value=model.percentage_change!,signed=`${value>0?"+":""}${value.toLocaleString("id-ID",{maximumFractionDigits:1})}%`,season=model.comparison_season_id!.replace("MT1","MT I").replace("MT2","MT II").replace("-"," ");return`${signed} dibanding ${season}`}
