"use client";
import { useCallback, useMemo, useRef, useState } from "react";
import { CloudSun, X } from "lucide-react";
import { useDashboardFilters } from "@/components/DashboardFilterProvider";
import { useAccessibleModal } from "@/components/ui/useAccessibleModal";
import { getRegionById, regions } from "@/lib/data-foundation";
import { climateRiskMetadata, selectClimateRisks, type ClimateRiskRecord } from "@/lib/climate-risk-data";
import { paginate, stableSort } from "@/lib/monitoring-table";
type SortKey = "region" | "risk" | "score" | "area" | "until";
const PAGE_SIZE = 3;
function RiskModal({ detail, onClose, fallbackRef }: { detail: ClimateRiskRecord; onClose: () => void; fallbackRef: React.RefObject<HTMLElement | null> }) {
  const ref = useRef<HTMLDivElement>(null); useAccessibleModal(onClose, ref, fallbackRef);
  return <div className="monitoring-modal-overlay" onMouseDown={e => e.target === e.currentTarget && onClose()}><section ref={ref} className="monitoring-modal" role="dialog" aria-modal="true" aria-labelledby="risk-title" tabIndex={-1}><header><div><span>Risiko &amp; Iklim</span><h2 id="risk-title">Detail {detail.risk_type}</h2></div><button onClick={onClose} aria-label={`Tutup detail risiko ${detail.risk_type}`}><X size={20} aria-hidden="true" /></button></header><div className="monitoring-modal-body detail-metrics">
    {[['Identitas',detail.id],['Wilayah',getRegionById(detail.region_id)?.name],['Musim',detail.season_id],['Formula skor',`${detail.likelihood} × ${detail.impact} = ${detail.risk_score}`],['Tingkat',detail.risk_level],['Status peringatan',detail.alert_status],['Status monitoring',detail.monitoring_status],['Status validasi',detail.validation_status],['Source type',detail.source_type],['Data type',detail.data_type],['Updated at',detail.updated_at],['Cut-off status',climateRiskMetadata.cutoff_date],['Periode',`${detail.valid_from}—${detail.valid_until ?? 'Belum tersedia'}`],['Luas',detail.affected_area_ha===null?'Belum tersedia':`${detail.affected_area_ha} ha`]].map(([label,value])=><p key={label}><b>{label}</b><span>{value??'Belum tersedia'}</span></p>)}
    <p className="detail-wide"><b>Source reference</b><span>{detail.source_reference}</span></p><div className="detail-wide"><b>Rekomendasi berbasis aturan</b><ul>{detail.recommendations.map(x=><li key={x}>{x}</li>)}</ul></div><p className="detail-wide simulation-disclaimer">Peringatan dini berbasis aturan data prototipe, bukan peringatan resmi BMKG/BPBD.</p>
  </div><footer><button onClick={onClose}>Tutup</button></footer></section></div>;
}
export default function RiskClimatePage() {
  const { filters, setSeason, setDistrict } = useDashboardFilters(); const headingRef=useRef<HTMLHeadingElement>(null);
  const [type,setType]=useState("all"),[level,setLevel]=useState("all"),[alert,setAlert]=useState("all"),[validation,setValidation]=useState("all"),[query,setQuery]=useState("");
  const [sort,setSort]=useState<SortKey>("score"),[asc,setAsc]=useState(false),[page,setPage]=useState(1),[detail,setDetail]=useState<{item:ClimateRiskRecord;context:string}|null>(null);
  const close=useCallback(()=>setDetail(null),[]); const contextKey=`${filters.seasonId}:${filters.regencyId}:${filters.districtId}:${filters.villageId}`;
  const selected=useMemo(()=>selectClimateRisks(filters.seasonId,filters.districtId??"93.01"),[filters.seasonId,filters.districtId]);
  const filtered=useMemo(()=>selected.items.filter(x=>(type==="all"||x.risk_type===type)&&(level==="all"||x.risk_level===level)&&(alert==="all"||x.alert_status===alert)&&(validation==="all"||x.validation_status===validation)&&`${getRegionById(x.region_id)?.name} ${x.risk_type}`.toLowerCase().includes(query.toLowerCase())),[selected.items,type,level,alert,validation,query]);
  const items=useMemo(()=>stableSort(filtered,x=>sort==="region"?getRegionById(x.region_id)?.name:sort==="risk"?x.risk_type:sort==="score"?x.risk_score:sort==="area"?x.affected_area_ha:x.valid_until,asc?"asc":"desc"),[filtered,sort,asc]);
  const visibleDetail=detail?.context===contextKey&&items.some(x=>x.id===detail.item.id)?detail.item:null; const pagination=paginate(items,page,PAGE_SIZE);
  const local=(fn:(x:string)=>void)=>(x:string)=>{fn(x);setPage(1);close()}, sortBy=(key:SortKey)=>{setAsc(sort===key?!asc:true);setSort(key);setPage(1)};
  const districts=regions.filter(x=>x.parent_id==="93.01"&&x.administrative_type==="district"), aggregate=selected.aggregate;
  return <div className="monitoring-page risk-page"><div className="monitoring-heading"><CloudSun aria-hidden="true"/><div><span>SIMULASI PROTOTIPE · KABUPATEN MERAUKE</span><h1 ref={headingRef} tabIndex={-1}>RISIKO &amp; IKLIM</h1><p>Pemantauan Risiko Pertanian dan Peringatan Dini</p></div></div><p className="simulation-disclaimer">Peringatan dini berbasis aturan data prototipe, bukan peringatan resmi BMKG/BPBD.</p>
  <section className="monitoring-filters risk-filters" aria-label="Filter Risiko dan Iklim"><label>Musim<select value={filters.seasonId} onChange={e=>{close();setPage(1);setSeason(e.target.value)}}><option value="MT1-2026">MT I 2026</option><option value="MT2-2026">MT II 2026</option></select></label><label>Distrik<select value={filters.districtId??""} onChange={e=>{close();setPage(1);setDistrict(e.target.value||null)}}><option value="">Semua distrik terpantau</option>{districts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>{[["Jenis risiko",type,setType,["Kekeringan","Banjir/genangan","Hama dan penyakit","Ketersediaan air","Cuaca ekstrem"]],["Tingkat",level,setLevel,["Rendah","Sedang","Tinggi","Kritis"]],["Status peringatan",alert,setAlert,["Normal","Waspada","Siaga","Kritis","Selesai/Kedaluwarsa","Belum tersedia"]],["Validasi",validation,setValidation,["approved","pending"]]].map(([label,value,setter,options])=><label key={label as string}>{label as string}<select value={value as string} onChange={e=>local(setter as (x:string)=>void)(e.target.value)}><option value="all">Semua</option>{(options as string[]).map(x=><option key={x}>{x}</option>)}</select></label>)}<label>Pencarian<input value={query} onChange={e=>local(setQuery)(e.target.value)} aria-label="Cari wilayah atau peringatan"/></label></section>
  {!selected.monitored?<section className="compact-empty-state" role="status"><div><h2>Wilayah belum dipantau</h2><p>Data risiko dan iklim untuk Distrik {getRegionById(filters.districtId??"")?.name} belum tersedia pada cakupan prototipe.</p></div></section>:<>{aggregate&&<section className="monitoring-kpis">{[["Peringatan aktif",aggregate.activeAlertCount],["Wilayah Siaga/Kritis",aggregate.severeRegionCount],["Luas berisiko",`${aggregate.affectedAreaHa.toLocaleString("id-ID")} ha`],["Risiko dominan",aggregate.dominantRisk],["Data tervalidasi",`${aggregate.validationPercent?.toLocaleString("id-ID")}%`],["Pembaruan terakhir",aggregate.latestUpdate??"Belum tersedia"]].map(([l,v])=><article key={l}><span>{l}</span><strong>{v}</strong></article>)}</section>}
  <section className="monitoring-grid two"><article className="monitoring-card"><h2>Ringkasan Iklim</h2><p className="card-copy">{aggregate?.climateSummary}</p></article><article className="monitoring-card"><h2>Komposisi Risiko</h2><div className="risk-composition">{aggregate?.riskComposition.map(x=><span key={x.level}><b>{x.level}</b>{x.count} record</span>)}</div></article></section>
  <section className="monitoring-card monitoring-table"><h2>Daftar Early Warning</h2><div className="table-scroll"><table><thead><tr>{[["region","Wilayah"],["risk","Jenis Risiko"],["score","Skor"],["area","Luas Terdampak"],["until","Periode"]].map(([k,l])=><th key={k} aria-sort={sort===k?(asc?"ascending":"descending"):"none"}><button onClick={()=>sortBy(k as SortKey)}>{l}</button></th>)}<th>Tingkat</th><th>Status</th><th>Validasi</th><th>Detail</th></tr></thead><tbody>{pagination.items.map(x=><tr key={x.id}><td>{getRegionById(x.region_id)?.name}</td><td>{x.risk_type}</td><td>{x.risk_score}</td><td>{x.affected_area_ha===null?"Belum tersedia":`${x.affected_area_ha} ha`}</td><td>{x.valid_from}—{x.valid_until??"Belum tersedia"}</td><td>{x.risk_level}</td><td>{x.alert_status}</td><td>{x.validation_status}</td><td><button onClick={()=>setDetail({item:x,context:contextKey})} aria-label={`Buka detail risiko ${x.risk_type} ${getRegionById(x.region_id)?.name}`}>Detail</button></td></tr>)}</tbody></table>{!items.length&&<p className="table-empty">Tidak ada data sesuai filter.</p>}</div>{items.length>0&&<div className="table-pagination"><span>Menampilkan {(pagination.page-1)*PAGE_SIZE+1}–{Math.min(pagination.page*PAGE_SIZE,items.length)} dari {items.length}</span><div><button disabled={!pagination.hasPrevious} aria-label="Halaman risiko sebelumnya" onClick={()=>setPage(x=>x-1)}>Sebelumnya</button>{Array.from({length:pagination.pageCount},(_,i)=><button key={i} aria-current={pagination.page===i+1?"page":undefined} onClick={()=>setPage(i+1)}>{i+1}</button>)}<button disabled={!pagination.hasNext} aria-label="Halaman risiko berikutnya" onClick={()=>setPage(x=>x+1)}>Berikutnya</button></div></div>}</section></>}
  {visibleDetail&&<RiskModal detail={visibleDetail} onClose={close} fallbackRef={headingRef}/>}</div>;
}
