"use client";
import { useCallback,useMemo,useRef,useState } from "react";
import { CloudSun,X } from "lucide-react";
import { useDashboardFilters } from "@/components/DashboardFilterProvider";
import { useAccessibleModal } from "@/components/ui/useAccessibleModal";
import { getRegionById,regions } from "@/lib/data-foundation";
import { climateRiskMetadata,selectClimateRisks,type ClimateRiskRecord } from "@/lib/climate-risk-data";
import { paginate,stableSort } from "@/lib/monitoring-table";
import { formatMonitoringDate,formatMonitoringDateRange,formatMonitoringPercent,formatMonitoringSeason,formatMonitoringStatus,formatMonitoringTimestamp } from "@/lib/monitoring-presentation";
type SortKey="region"|"risk"|"score"|"area"|"until";const PAGE_SIZE=3;
const badge=(value:string,kind:"level"|"validation"|"status"="status")=><span className={`status-badge status-${kind} status-${value.toLowerCase().replace(/[^a-z]+/g,"-")}`}>{kind==="validation"?formatMonitoringStatus(value):value}</span>;
function RiskModal({detail,onClose,fallbackRef}:{detail:ClimateRiskRecord;onClose:()=>void;fallbackRef:React.RefObject<HTMLElement|null>}){
 const ref=useRef<HTMLDivElement>(null);useAccessibleModal(onClose,ref,fallbackRef);
 const groups=[
  ["Identitas dan konteks",[["ID",detail.id],["Wilayah",getRegionById(detail.region_id)?.name],["Musim",formatMonitoringSeason(detail.season_id)]]],
  ["Penilaian risiko",[["Jenis risiko",detail.risk_type],["Formula skor",`${detail.likelihood} × ${detail.impact} = ${detail.risk_score}`],["Tingkat",detail.risk_level],["Status peringatan",detail.alert_status]]],
  ["Monitoring dan validasi",[["Status monitoring",formatMonitoringStatus(detail.monitoring_status)],["Status validasi",formatMonitoringStatus(detail.validation_status)],["Luas",detail.affected_area_ha===null?"Belum tersedia":`${detail.affected_area_ha.toLocaleString("id-ID")} ha`]]],
  ["Periode dan pembaruan",[["Periode",formatMonitoringDateRange(detail.valid_from,detail.valid_until)],["Diperbarui",formatMonitoringTimestamp(detail.updated_at)],["Cut-off",formatMonitoringDate(climateRiskMetadata.cutoff_date)]]],
  ["Sumber",[["Referensi",detail.source_reference],["Tipe sumber",formatMonitoringStatus(detail.source_type)],["Tipe data",formatMonitoringStatus(detail.data_type)]]],
 ] as const;
 return <div className="monitoring-modal-overlay" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section ref={ref} className="monitoring-modal monitoring-detail-modal" role="dialog" aria-modal="true" aria-labelledby="risk-title" tabIndex={-1}><header><div><span>Risiko &amp; Iklim</span><h2 id="risk-title">Detail {detail.risk_type}</h2></div><button onClick={onClose} aria-label={`Tutup detail risiko ${detail.risk_type}`}><X size={20} aria-hidden="true"/></button></header><div className="monitoring-modal-body detail-sections">{groups.map(([title,items])=><section key={title}><h3>{title}</h3><dl>{items.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value??"Belum tersedia"}</dd></div>)}</dl></section>)}<section><h3>Rekomendasi berbasis aturan</h3><ul>{detail.recommendations.map(item=><li key={item}>{item}</li>)}</ul></section><p className="simulation-disclaimer">Peringatan dini berbasis aturan data prototipe, bukan peringatan resmi BMKG/BPBD.</p></div><footer><button onClick={onClose}>Tutup</button></footer></section></div>;
}
export default function RiskClimatePage(){
 const{filters,setSeason,setDistrict}=useDashboardFilters();const headingRef=useRef<HTMLHeadingElement>(null);
 const[type,setType]=useState("all"),[level,setLevel]=useState("all"),[alert,setAlert]=useState("all"),[validation,setValidation]=useState("all"),[query,setQuery]=useState("");
 const[sort,setSort]=useState<SortKey>("score"),[asc,setAsc]=useState(false),[page,setPage]=useState(1),[detail,setDetail]=useState<{item:ClimateRiskRecord;context:string}|null>(null);const close=useCallback(()=>setDetail(null),[]),contextKey=`${filters.seasonId}:${filters.regencyId}:${filters.districtId}:${filters.villageId}`;
 const selected=useMemo(()=>selectClimateRisks(filters.seasonId,filters.districtId??"93.01"),[filters.seasonId,filters.districtId]);
 const filtered=useMemo(()=>selected.items.filter(item=>(type==="all"||item.risk_type===type)&&(level==="all"||item.risk_level===level)&&(alert==="all"||item.alert_status===alert)&&(validation==="all"||item.validation_status===validation)&&`${getRegionById(item.region_id)?.name} ${item.risk_type}`.toLowerCase().includes(query.toLowerCase())),[selected.items,type,level,alert,validation,query]);
 const items=useMemo(()=>stableSort(filtered,item=>sort==="region"?getRegionById(item.region_id)?.name:sort==="risk"?item.risk_type:sort==="score"?item.risk_score:sort==="area"?item.affected_area_ha:item.valid_until,asc?"asc":"desc"),[filtered,sort,asc]);
 const visibleDetail=detail?.context===contextKey&&items.some(item=>item.id===detail.item.id)?detail.item:null,pagination=paginate(items,page,PAGE_SIZE),local=(setter:(value:string)=>void)=>(value:string)=>{setter(value);setPage(1);close()},sortBy=(key:SortKey)=>{setAsc(sort===key?!asc:true);setSort(key);setPage(1)},districts=regions.filter(item=>item.parent_id==="93.01"&&item.administrative_type==="district"),aggregate=selected.aggregate;
 const sortable:[[SortKey,string],[SortKey,string],[SortKey,string],[SortKey,string],[SortKey,string]]=[["region","Wilayah"],["risk","Jenis Risiko"],["score","Skor"],["area","Luas Terdampak"],["until","Periode"]];
 return <div className="monitoring-page risk-page"><div className="monitoring-heading"><span className="monitoring-heading-icon"><CloudSun aria-hidden="true"/></span><div><span>SIMULASI PROTOTIPE · KABUPATEN MERAUKE</span><h1 ref={headingRef} tabIndex={-1}>RISIKO &amp; IKLIM</h1><p>Pemantauan Risiko Pertanian dan Peringatan Dini</p></div></div><p className="simulation-disclaimer">Peringatan dini berbasis aturan data prototipe, bukan peringatan resmi BMKG/BPBD.</p>
 <section className="monitoring-filters" aria-label="Filter Risiko dan Iklim"><label>Musim<select value={filters.seasonId} onChange={e=>{close();setPage(1);setSeason(e.target.value)}}><option value="MT1-2026">MT I 2026</option><option value="MT2-2026">MT II 2026</option></select></label><label>Distrik<select value={filters.districtId??""} onChange={e=>{close();setPage(1);setDistrict(e.target.value||null)}}><option value="">Semua distrik terpantau</option>{districts.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>{[["Jenis risiko",type,setType,["Kekeringan","Banjir/genangan","Hama dan penyakit","Ketersediaan air","Cuaca ekstrem"]],["Tingkat",level,setLevel,["Rendah","Sedang","Tinggi","Kritis"]],["Status peringatan",alert,setAlert,["Normal","Waspada","Siaga","Kritis","Selesai/Kedaluwarsa","Belum tersedia"]],["Validasi",validation,setValidation,["approved","pending"]]].map(([labelText,value,setter,options])=><label key={labelText as string}>{labelText as string}<select value={value as string} onChange={e=>local(setter as (value:string)=>void)(e.target.value)}><option value="all">Semua</option>{(options as string[]).map(option=><option key={option} value={option}>{formatMonitoringStatus(option)}</option>)}</select></label>)}<label className="monitoring-search-field">Pencarian<input className="monitoring-search" value={query} onChange={e=>local(setQuery)(e.target.value)} placeholder="Cari wilayah atau risiko" aria-label="Cari wilayah atau peringatan"/></label></section>
 {!selected.monitored?<section className="compact-empty-state" role="status"><div><h2>Wilayah belum dipantau</h2><p>Data risiko dan iklim untuk Distrik {getRegionById(filters.districtId??"")?.name} belum tersedia pada cakupan prototipe.</p></div></section>:<>{aggregate&&<section className="monitoring-kpis">{[["Peringatan aktif",aggregate.activeAlertCount],["Wilayah Siaga/Kritis",aggregate.severeRegionCount],["Luas berisiko",`${aggregate.affectedAreaHa.toLocaleString("id-ID")} ha`],["Risiko dominan",aggregate.dominantRisk],["Data tervalidasi",formatMonitoringPercent(aggregate.validationPercent)],["Pembaruan terakhir",formatMonitoringTimestamp(aggregate.latestUpdate)]].map(([labelText,value])=><article key={labelText}><span>{labelText}</span><strong>{value}</strong></article>)}</section>}
 <section className="monitoring-grid two risk-summary-grid"><article className="monitoring-card climate-summary"><h2>Ringkasan Iklim</h2><p className="card-copy">{aggregate?.climateSummary}</p></article><article className="monitoring-card"><h2>Komposisi Risiko</h2><div className="risk-composition">{aggregate?.riskComposition.map(item=><span key={item.level} data-level={item.level.toLowerCase()}><i aria-hidden="true"/><b>{item.level}</b><strong>{item.count}</strong><small>record</small></span>)}</div></article></section>
 <section className="monitoring-card monitoring-table risk-table"><h2>Daftar Early Warning</h2><div className="table-scroll"><table><thead><tr>{sortable.map(([key,labelText])=><th key={key} aria-sort={sort===key?(asc?"ascending":"descending"):"none"}><button className="table-sort" onClick={()=>sortBy(key)}>{labelText}<span aria-hidden="true">{sort===key?(asc?"↑":"↓"):"↕"}</span></button></th>)}<th>Tingkat</th><th>Status</th><th>Validasi</th><th>Detail</th></tr></thead><tbody>{pagination.items.map(item=><tr key={item.id}><td>{getRegionById(item.region_id)?.name}</td><td>{item.risk_type}</td><td className="numeric-cell">{item.risk_score}</td><td className="numeric-cell">{item.affected_area_ha===null?"Belum tersedia":`${item.affected_area_ha.toLocaleString("id-ID")} ha`}</td><td>{formatMonitoringDateRange(item.valid_from,item.valid_until)}</td><td>{badge(item.risk_level,"level")}</td><td>{badge(item.alert_status)}</td><td>{badge(item.validation_status,"validation")}</td><td><button onClick={()=>setDetail({item,context:contextKey})} aria-label={`Buka detail risiko ${item.risk_type} ${getRegionById(item.region_id)?.name}`}>Detail</button></td></tr>)}</tbody></table>{!items.length&&<p className="table-empty">Tidak ada data sesuai filter.</p>}</div>{items.length>0&&<div className="table-pagination"><span>Menampilkan {(pagination.page-1)*PAGE_SIZE+1}–{Math.min(pagination.page*PAGE_SIZE,items.length)} dari {items.length}</span><div><button disabled={!pagination.hasPrevious} aria-label="Halaman risiko sebelumnya" onClick={()=>setPage(value=>value-1)}>Sebelumnya</button>{Array.from({length:pagination.pageCount},(_,index)=><button key={index} aria-current={pagination.page===index+1?"page":undefined} onClick={()=>setPage(index+1)}>{index+1}</button>)}<button disabled={!pagination.hasNext} aria-label="Halaman risiko berikutnya" onClick={()=>setPage(value=>value+1)}>Berikutnya</button></div></div>}</section></>}
 {visibleDetail&&<RiskModal detail={visibleDetail} onClose={close} fallbackRef={headingRef}/>}</div>;
}
