"use client";

import { useMemo, useRef, useState, type Dispatch, type SetStateAction } from "react";
import { ArrowDown, ArrowUp, ArrowUpDown, Droplets, MapPinOff, Tractor, Wrench, X } from "lucide-react";
import { useDashboardFilters } from "@/components/DashboardFilterProvider";
import { useAccessibleModal } from "@/components/ui/useAccessibleModal";
import { getRegionById, regions } from "@/lib/data-foundation";
import {
  compareInfrastructureValues, dominantIrrigationCondition, equipmentCategories, filterIrrigationRows,
  filterProductionInputRows, formatInfrastructureValue, inputFulfillment, irrigationMetadata,
  paginateRows, selectIrrigation, selectProductionInputs, type IrrigationCondition, type IrrigationRecord,
  type ProductionInputRecord, type SortDirection, type ValidationStatusFilter,
} from "@/lib/infrastructure-data";
import { formatMonitoringDate, formatMonitoringStatus, formatMonitoringTimestamp } from "@/lib/monitoring-presentation";

const districts = regions.filter(region => region.parent_id === "93.01" && region.administrative_type === "district");
const PAGE_SIZE = 10;
type Detail = { kind: "irrigation"; item: IrrigationRecord } | { kind: "input"; item: ProductionInputRecord };
type IrrigationSort = "network"|"region"|"service"|"length"|"good"|"light"|"heavy"|"water"|"validation"|"updated";
type InputSort = "item"|"category"|"region"|"required"|"available"|"fulfillment"|"ready"|"repair"|"validation"|"updated";
const validationLabel = formatMonitoringStatus;
const dateId = formatMonitoringTimestamp;
const conditionLabel = (value: IrrigationCondition) => value === "good" ? "Baik" : value === "light_damage" ? "Rusak Ringan" : "Rusak Berat";

function SortHeader<K extends string>({ label, field, active, direction, onSort }: { label:string; field:K; active:K; direction:SortDirection; onSort:(field:K)=>void }) {
  const ariaSort = active === field ? (direction === "asc" ? "ascending" : "descending") : "none";
  const SortIcon = active !== field ? ArrowUpDown : direction === "asc" ? ArrowUp : ArrowDown;
  return <th aria-sort={ariaSort}><button className="table-sort" onClick={() => onSort(field)}>{label}<SortIcon size={14} aria-hidden="true"/></button></th>;
}

function Pagination({ page, totalPages, start, end, total, onPage }: { page:number; totalPages:number; start:number; end:number; total:number; onPage:(page:number)=>void }) {
  if (total <= PAGE_SIZE) return null;
  return <nav className="table-pagination" aria-label="Pagination tabel"><p>Menampilkan {start}–{end} dari {total} data</p><div><button onClick={() => onPage(page - 1)} disabled={page === 1} aria-label="Halaman sebelumnya">Previous</button>{Array.from({length:totalPages},(_,index)=>index+1).map(number=><button key={number} onClick={()=>onPage(number)} aria-label={`Halaman ${number}`} aria-current={number===page?"page":undefined}>{number}</button>)}<button onClick={() => onPage(page + 1)} disabled={page === totalPages} aria-label="Halaman berikutnya">Next</button></div></nav>;
}

function UnmonitoredPanel({ type, district, onChoose }: { type:"Irigasi"|"Sarana Produksi"; district:string; onChoose:()=>void }) {
  return <section className="compact-empty-state" role="status"><MapPinOff size={28} aria-hidden="true"/><div><h2>Wilayah belum dipantau</h2><p>Data {type} untuk Distrik {district} belum tersedia pada cakupan prototipe.</p><small>Pilih wilayah terpantau untuk melihat indikator dan rincian data.</small><button onClick={onChoose}>Pilih wilayah terpantau</button></div></section>;
}

function InfrastructureDetail({ detail, onClose }: { detail: Detail; onClose: () => void }) {
  const dialogRef = useRef<HTMLDivElement>(null);
  useAccessibleModal(onClose, dialogRef);
  const irrigation = detail.kind === "irrigation" ? detail.item : null;
  const input = detail.kind === "input" ? detail.item : null;
  const fulfillment = input ? inputFulfillment(input) : null;
  return <div className="monitoring-modal-backdrop" onMouseDown={event => event.target === event.currentTarget && onClose()}><div ref={dialogRef} className="monitoring-modal" role="dialog" aria-modal="true" aria-labelledby="infra-detail-title" tabIndex={-1}>
    <header><div><span>Infrastruktur &amp; Sarana</span><h2 id="infra-detail-title">{irrigation?.network_name ?? input?.item_name}</h2></div><button onClick={onClose} aria-label={`Tutup detail ${irrigation?.network_name ?? input?.item_name}`}><X size={20} aria-hidden="true" /></button></header>
    <div className="monitoring-modal-body">
      {irrigation && <><h3>Identitas</h3><dl className="detail-metrics"><div><dt>Wilayah</dt><dd>{getRegionById(irrigation.region_id)?.name}</dd></div><div><dt>Musim</dt><dd>{irrigation.season_id === "MT1-2026" ? "MT I 2026" : "MT II 2026"}</dd></div><div><dt>Kewenangan</dt><dd>{irrigation.authority}</dd></div><div><dt>Pengelola</dt><dd>{irrigation.management_agency}</dd></div><div><dt>Sumber air</dt><dd>{irrigation.water_source}</dd></div></dl>
      <h3>Cakupan</h3><dl className="detail-metrics"><div><dt>Panjang jaringan</dt><dd>{formatInfrastructureValue(irrigation.network_length_km,"km")}</dd></div><div><dt>Luas layanan</dt><dd>{formatInfrastructureValue(irrigation.service_area_ha,"ha")}</dd></div><div><dt>Kondisi baik</dt><dd>{formatInfrastructureValue(irrigation.good_condition_km,"km")}</dd></div><div><dt>Rusak ringan</dt><dd>{formatInfrastructureValue(irrigation.light_damage_km,"km")}</dd></div><div><dt>Rusak berat</dt><dd>{formatInfrastructureValue(irrigation.heavy_damage_km,"km")}</dd></div></dl>
      <h3>Operasional dan validasi</h3><dl className="detail-metrics"><div><dt>Kecukupan air</dt><dd>{formatInfrastructureValue(irrigation.water_adequacy_pct,"%")}</dd></div><div><dt>Tingkat fungsional</dt><dd>{formatInfrastructureValue(irrigation.functional_pct,"%")}</dd></div><div><dt>Pemeriksaan terakhir</dt><dd>{formatMonitoringDate(irrigation.last_inspection_at)}</dd></div><div><dt>Status monitoring</dt><dd>{formatMonitoringStatus(irrigation.monitoring_status)}</dd></div><div><dt>Status validasi</dt><dd>{formatMonitoringStatus(irrigation.validation_status)}</dd></div><div><dt>Sumber data</dt><dd>{irrigation.source_reference}</dd></div><div><dt>Diperbarui</dt><dd>{formatMonitoringTimestamp(irrigation.updated_at)}</dd></div></dl>
      <h3>Formula dan keterangan</h3><p>Total kondisi = baik + rusak ringan + rusak berat. Toleransi rekonsiliasi {irrigationMetadata.rounding_tolerance_km.toLocaleString("id-ID")} km. Kondisi dominan ({conditionLabel(dominantIrrigationCondition(irrigation))}) dihitung dari panjang terbesar.</p></>}
      {input && <><h3>Identitas</h3><dl className="detail-metrics"><div><dt>Kategori</dt><dd>{input.category}</dd></div><div><dt>Nama item</dt><dd>{input.item_name}</dd></div><div><dt>Unit</dt><dd>{input.unit}</dd></div><div><dt>Wilayah</dt><dd>{getRegionById(input.region_id)?.name}</dd></div><div><dt>Musim</dt><dd>{input.season_id === "MT1-2026" ? "MT I 2026" : "MT II 2026"}</dd></div></dl>
      <h3>Kebutuhan dan distribusi</h3><dl className="detail-metrics"><div><dt>Kebutuhan</dt><dd>{formatInfrastructureValue(input.required_quantity,input.unit)}</dd></div><div><dt>Tersedia</dt><dd>{formatInfrastructureValue(input.available_quantity,input.unit)}</dd></div><div><dt>Tersalurkan</dt><dd>{formatInfrastructureValue(input.distributed_quantity,input.unit)}</dd></div><div><dt>Kekurangan</dt><dd>{formatInfrastructureValue(Math.max(0,input.required_quantity-input.available_quantity),input.unit)}</dd></div><div><dt>Persentase pemenuhan</dt><dd>{formatInfrastructureValue(fulfillment?.presentationPct??null,"%")}</dd></div></dl>
      {equipmentCategories.has(input.category) && <><h3>Kondisi alat</h3><dl className="detail-metrics"><div><dt>Siap</dt><dd>{formatInfrastructureValue(input.ready_quantity,input.unit)}</dd></div><div><dt>Rusak ringan</dt><dd>{formatInfrastructureValue(input.light_damage_quantity,input.unit)}</dd></div><div><dt>Rusak berat</dt><dd>{formatInfrastructureValue(input.heavy_damage_quantity,input.unit)}</dd></div></dl></>}
      <h3>Kelembagaan dan validasi</h3><dl className="detail-metrics"><div><dt>Jenis pemilik</dt><dd>{input.owner_type}</dd></div><div><dt>Unit pengelola</dt><dd>{input.management_unit}</dd></div><div><dt>Penerima</dt><dd>{input.beneficiary}</dd></div><div><dt>Verifikasi terakhir</dt><dd>{formatMonitoringDate(input.last_verified_at)}</dd></div><div><dt>Status validasi</dt><dd>{formatMonitoringStatus(input.validation_status)}</dd></div><div><dt>Sumber</dt><dd>{input.source_reference}</dd></div><div><dt>Diperbarui</dt><dd>{formatMonitoringTimestamp(input.updated_at)}</dd></div></dl>
      {input.required_quantity > 0 && <><h3>Formula dan keterangan</h3><p>Pemenuhan = tersedia ÷ kebutuhan × 100. Kuantitas dengan unit berbeda tidak dijumlahkan.</p></>}</>}
      <p className="simulation-disclaimer">Data simulasi prototipe tingkat distrik; penyebab kondisi tidak difabrikasi.</p>
    </div><footer><button onClick={onClose}>Tutup</button></footer>
  </div></div>;
}

export default function InfrastructurePage() {
  const { filters, setSeason, setDistrict } = useDashboardFilters();
  const [tab, setTab] = useState<"irrigation"|"inputs">("irrigation");
  const [category, setCategory] = useState("all");
  const [query, setQuery] = useState("");
  const [irrigationCondition, setIrrigationCondition] = useState<"all"|IrrigationCondition>("all");
  const [irrigationValidation, setIrrigationValidation] = useState<ValidationStatusFilter>("all");
  const [inputValidation, setInputValidation] = useState<ValidationStatusFilter>("all");
  const [irrigationSort, setIrrigationSort] = useState<{field:IrrigationSort;direction:SortDirection}>({field:"region",direction:"asc"});
  const [inputSort, setInputSort] = useState<{field:InputSort;direction:SortDirection}>({field:"fulfillment",direction:"asc"});
  const [page, setPage] = useState(1);
  const [detail, setDetail] = useState<Detail | null>(null);
  const irrigation = useMemo(() => selectIrrigation(filters.seasonId, filters.districtId ?? "93.01"), [filters.seasonId, filters.districtId]);
  const inputs = useMemo(() => selectProductionInputs(filters.seasonId, filters.districtId ?? "93.01", category), [filters.seasonId, filters.districtId, category]);
  const changeSort = <K extends string>(setter: Dispatch<SetStateAction<{field:K;direction:SortDirection}>>) => (field:K) => { setter(current => ({field,direction:current.field===field&&current.direction==="asc"?"desc":"asc"})); setPage(1); };
  const irrigationRows = useMemo(() => filterIrrigationRows(irrigation.items,query,irrigationCondition,irrigationValidation).slice().sort((a,b)=>{
    const value=(row:IrrigationRecord):string|number|null=>({network:row.network_name,region:getRegionById(row.region_id)?.name??null,service:row.service_area_ha,length:row.network_length_km,good:row.good_condition_km,light:row.light_damage_km,heavy:row.heavy_damage_km,water:row.water_adequacy_pct,validation:row.validation_status,updated:Date.parse(row.updated_at)}[irrigationSort.field]);
    const primary=compareInfrastructureValues(value(a),value(b),irrigationSort.direction); return primary || a.network_name.localeCompare(b.network_name,"id-ID");
  }),[irrigation.items,query,irrigationCondition,irrigationValidation,irrigationSort]);
  const inputRows = useMemo(() => filterProductionInputRows(inputs.items,query,inputValidation).slice().sort((a,b)=>{
    const value=(row:ProductionInputRecord):string|number|null=>({item:row.item_name,category:row.category,region:getRegionById(row.region_id)?.name??null,required:row.required_quantity,available:row.available_quantity,fulfillment:inputFulfillment(row)?.presentationPct??null,ready:equipmentCategories.has(row.category)?row.ready_quantity:null,repair:equipmentCategories.has(row.category)?row.light_damage_quantity+row.heavy_damage_quantity:null,validation:row.validation_status,updated:Date.parse(row.updated_at)}[inputSort.field]);
    return compareInfrastructureValues(value(a),value(b),inputSort.direction);
  }),[inputs.items,query,inputValidation,inputSort]);
  const irrigationPage=paginateRows(irrigationRows,page,PAGE_SIZE), inputPage=paginateRows(inputRows,page,PAGE_SIZE);
  const i=irrigation.aggregate,p=inputs.aggregate;
  const irrigationKpis=[["Luas Layanan",i?.serviceAreaHa??null,"ha"],["Total Jaringan",i?.networkLengthKm??null,"km"],["Kondisi Baik",i?.goodKm??null,"km"],["Rusak Ringan",i?.lightDamageKm??null,"km"],["Rusak Berat",i?.heavyDamageKm??null,"km"],["Kecukupan Air",i?.waterAdequacyPct??null,"%"],["Validasi",i?i.approved/i.total*100:null,"%"]] as const;
  const inputKpis=[["Kategori Dipantau",p?.categoryCount??null,"kategori"],["Kategori Terpenuhi",p?.fulfilledCategories??null,"kategori"],["Rata-rata Pemenuhan",p?.averageFulfillmentPct??null,"%"],["Alsintan Siap Pakai",p?.equipmentReady??null,"unit"],["Perlu Perbaikan",p?.equipmentNeedsRepair??null,"unit"],["Wilayah Kekurangan",p?.shortageRegions??null,"wilayah"],["Validasi",p?p.approved/p.total*100:null,"%"]] as const;
  return <div className="monitoring-page infrastructure-page">
    <header className="monitoring-heading"><div><span>SIMULASI PROTOTIPE · KABUPATEN MERAUKE</span><h1>INFRASTRUKTUR &amp; SARANA</h1><p>Pemantauan Irigasi dan Sarana Produksi Pertanian</p></div><Wrench size={34} aria-hidden="true" /></header>
    <section className="monitoring-filters" aria-label="Filter Infrastruktur dan Sarana"><label>Musim<select value={filters.seasonId} onChange={event=>{setPage(1);setSeason(event.target.value)}}><option value="MT2-2026">MT II 2026</option><option value="MT1-2026">MT I 2026</option></select></label><label>Kabupaten<select disabled><option>Kabupaten Merauke</option></select></label><label>Distrik<select value={filters.districtId??""} onChange={event=>{setPage(1);setDistrict(event.target.value||null)}}><option value="">Semua distrik terpantau</option>{districts.map(region=><option value={region.id} key={region.id}>{region.name}{region.monitoring_status!=="active"?" — Belum dipantau":""}</option>)}</select></label><label>Pencarian<input className="monitoring-search" value={query} onChange={event=>{setPage(1);setQuery(event.target.value)}} placeholder="Cari wilayah atau item" aria-label="Cari wilayah atau item" /></label></section>
    <div className="monitoring-tabs" role="tablist" aria-label="Jenis pemantauan"><button role="tab" aria-selected={tab==="irrigation"} onClick={()=>{setPage(1);setTab("irrigation")}}><Droplets size={18} aria-hidden="true"/> Irigasi</button><button role="tab" aria-selected={tab==="inputs"} onClick={()=>{setPage(1);setTab("inputs")}}><Tractor size={18} aria-hidden="true"/> Sarana Produksi</button></div>
    {tab==="irrigation"&&!irrigation.monitored&&<><div className="local-filters"><label>Kondisi<select value={irrigationCondition} onChange={event=>setIrrigationCondition(event.target.value as "all"|IrrigationCondition)}><option value="all">Semua Kondisi</option><option value="good">Baik</option><option value="light_damage">Rusak Ringan</option><option value="heavy_damage">Rusak Berat</option></select></label><label>Validasi<select value={irrigationValidation} onChange={event=>setIrrigationValidation(event.target.value as ValidationStatusFilter)}><option value="all">Semua Validasi</option><option value="approved">Disetujui</option><option value="pending">Menunggu</option><option value="rejected">Ditolak</option></select></label></div><UnmonitoredPanel type="Irigasi" district={getRegionById(filters.districtId??"")?.name??"terpilih"} onChoose={()=>document.querySelector<HTMLSelectElement>('.infrastructure-page .monitoring-filters label:nth-child(3) select')?.focus()}/></>}
    {tab==="inputs"&&!inputs.monitored&&<><div className="local-filters"><label>Kategori<select value={category} onChange={event=>setCategory(event.target.value)}><option value="all">Semua kategori</option>{["Benih","Pupuk","Pestisida","Traktor","Combine Harvester","Pompa Air"].map(value=><option key={value}>{value}</option>)}</select></label><label>Validasi<select value={inputValidation} onChange={event=>setInputValidation(event.target.value as ValidationStatusFilter)}><option value="all">Semua Validasi</option><option value="approved">Disetujui</option><option value="pending">Menunggu</option><option value="rejected">Ditolak</option></select></label></div><UnmonitoredPanel type="Sarana Produksi" district={getRegionById(filters.districtId??"")?.name??"terpilih"} onChoose={()=>document.querySelector<HTMLSelectElement>('.infrastructure-page .monitoring-filters label:nth-child(3) select')?.focus()}/></>}
    {(tab==="irrigation"?irrigation.monitored:inputs.monitored)&&(tab==="irrigation"?<><div className="local-filters"><label>Kondisi<select value={irrigationCondition} onChange={event=>{setPage(1);setIrrigationCondition(event.target.value as "all"|IrrigationCondition)}}><option value="all">Semua Kondisi</option><option value="good">Baik</option><option value="light_damage">Rusak Ringan</option><option value="heavy_damage">Rusak Berat</option></select></label><label>Validasi<select value={irrigationValidation} onChange={event=>{setPage(1);setIrrigationValidation(event.target.value as ValidationStatusFilter)}}><option value="all">Semua Validasi</option><option value="approved">Disetujui</option><option value="pending">Menunggu</option><option value="rejected">Ditolak</option></select></label></div>
      <section className="monitoring-kpis seven">{irrigationKpis.map(([label,value,unit])=><article key={label}><i><Droplets size={19} aria-hidden="true"/></i><span>{label}</span><strong>{formatInfrastructureValue(value,unit)}</strong></article>)}</section>
      {!irrigation.monitored?<div className="monitoring-empty">Belum dipantau</div>:<><section className="monitoring-grid two"><article className="monitoring-card"><h2>Komposisi Kondisi Irigasi</h2><div className="condition-stack"><i style={{width:`${i!.goodKm/i!.networkLengthKm*100}%`}}/><i className="light" style={{width:`${i!.lightDamageKm/i!.networkLengthKm*100}%`}}/><i className="heavy" style={{width:`${i!.heavyDamageKm/i!.networkLengthKm*100}%`}}/></div><p className="card-copy">Baik {formatInfrastructureValue(i!.goodKm,"km")} · Ringan {formatInfrastructureValue(i!.lightDamageKm,"km")} · Berat {formatInfrastructureValue(i!.heavyDamageKm,"km")}</p></article><article className="monitoring-card"><h2>Layanan dan Kecukupan Air</h2><p className="large-stat">{formatInfrastructureValue(i!.serviceAreaHa,"ha")}</p><p className="card-copy">Kecukupan air {formatInfrastructureValue(i!.waterAdequacyPct,"%")}</p></article></section>
      <section className="monitoring-card monitoring-table"><h2>Daftar Jaringan Irigasi</h2>{irrigationRows.length?<><div className="table-scroll"><table><thead><tr><SortHeader label="Jaringan" field="network" active={irrigationSort.field} direction={irrigationSort.direction} onSort={changeSort(setIrrigationSort)}/><SortHeader label="Wilayah" field="region" active={irrigationSort.field} direction={irrigationSort.direction} onSort={changeSort(setIrrigationSort)}/><SortHeader label="Luas Layanan" field="service" active={irrigationSort.field} direction={irrigationSort.direction} onSort={changeSort(setIrrigationSort)}/><SortHeader label="Panjang" field="length" active={irrigationSort.field} direction={irrigationSort.direction} onSort={changeSort(setIrrigationSort)}/><SortHeader label="Baik" field="good" active={irrigationSort.field} direction={irrigationSort.direction} onSort={changeSort(setIrrigationSort)}/><SortHeader label="Rusak Ringan" field="light" active={irrigationSort.field} direction={irrigationSort.direction} onSort={changeSort(setIrrigationSort)}/><SortHeader label="Rusak Berat" field="heavy" active={irrigationSort.field} direction={irrigationSort.direction} onSort={changeSort(setIrrigationSort)}/><SortHeader label="Kecukupan Air" field="water" active={irrigationSort.field} direction={irrigationSort.direction} onSort={changeSort(setIrrigationSort)}/><SortHeader label="Validasi" field="validation" active={irrigationSort.field} direction={irrigationSort.direction} onSort={changeSort(setIrrigationSort)}/><SortHeader label="Pembaruan" field="updated" active={irrigationSort.field} direction={irrigationSort.direction} onSort={changeSort(setIrrigationSort)}/><th>Detail</th></tr></thead><tbody>{irrigationPage.rows.map(item=><tr key={item.id}><td>{item.network_name}</td><td>{getRegionById(item.region_id)?.name}</td><td>{formatInfrastructureValue(item.service_area_ha,"ha")}</td><td>{formatInfrastructureValue(item.network_length_km,"km")}</td><td>{formatInfrastructureValue(item.good_condition_km,"km")}</td><td>{formatInfrastructureValue(item.light_damage_km,"km")}</td><td>{formatInfrastructureValue(item.heavy_damage_km,"km")}</td><td>{formatInfrastructureValue(item.water_adequacy_pct,"%")}</td><td>{validationLabel(item.validation_status)}</td><td>{dateId(item.updated_at)}</td><td><button onClick={()=>setDetail({kind:"irrigation",item})} aria-label={`Detail irigasi ${item.network_name}`}>Detail</button></td></tr>)}</tbody></table></div><Pagination page={irrigationPage.currentPage} totalPages={irrigationPage.totalPages} start={irrigationPage.start} end={irrigationPage.end} total={irrigationPage.total} onPage={setPage}/></>:<div className="table-empty" role="status">Tidak ada data sesuai filter.</div>}</section></>}
    </>:<><div className="local-filters"><label>Kategori<select value={category} onChange={event=>{setPage(1);setCategory(event.target.value)}}><option value="all">Semua kategori</option>{["Benih","Pupuk","Pestisida","Traktor","Combine Harvester","Pompa Air"].map(value=><option key={value}>{value}</option>)}</select></label><label>Validasi<select value={inputValidation} onChange={event=>{setPage(1);setInputValidation(event.target.value as ValidationStatusFilter)}}><option value="all">Semua Validasi</option><option value="approved">Disetujui</option><option value="pending">Menunggu</option><option value="rejected">Ditolak</option></select></label></div>
      <section className="monitoring-kpis seven">{inputKpis.map(([label,value,unit])=><article key={label}><i><Tractor size={19} aria-hidden="true"/></i><span>{label}</span><strong>{formatInfrastructureValue(value,unit)}</strong></article>)}</section>
      {!inputs.monitored?<div className="monitoring-empty">Belum dipantau</div>:<><section className="monitoring-grid two"><article className="monitoring-card"><h2>Kebutuhan vs Ketersediaan</h2><p className="large-stat">{formatInfrastructureValue(p!.averageFulfillmentPct,"%")}</p><p className="card-copy">Rata-rata persentase kategori; kuantitas berbeda unit tidak dijumlahkan.</p></article><article className="monitoring-card"><h2>Status Alsintan</h2><p className="large-stat">{formatInfrastructureValue(p!.equipmentReady,"unit")}</p><p className="card-copy">Perlu perbaikan {formatInfrastructureValue(p!.equipmentNeedsRepair,"unit")}</p></article></section>
      <section className="monitoring-card monitoring-table"><h2>Daftar Sarana Produksi</h2>{inputRows.length?<><div className="table-scroll"><table><thead><tr><SortHeader label="Item" field="item" active={inputSort.field} direction={inputSort.direction} onSort={changeSort(setInputSort)}/><SortHeader label="Kategori" field="category" active={inputSort.field} direction={inputSort.direction} onSort={changeSort(setInputSort)}/><SortHeader label="Wilayah" field="region" active={inputSort.field} direction={inputSort.direction} onSort={changeSort(setInputSort)}/><SortHeader label="Kebutuhan" field="required" active={inputSort.field} direction={inputSort.direction} onSort={changeSort(setInputSort)}/><SortHeader label="Tersedia" field="available" active={inputSort.field} direction={inputSort.direction} onSort={changeSort(setInputSort)}/><SortHeader label="Pemenuhan" field="fulfillment" active={inputSort.field} direction={inputSort.direction} onSort={changeSort(setInputSort)}/><SortHeader label="Siap" field="ready" active={inputSort.field} direction={inputSort.direction} onSort={changeSort(setInputSort)}/><SortHeader label="Perlu Perbaikan" field="repair" active={inputSort.field} direction={inputSort.direction} onSort={changeSort(setInputSort)}/><SortHeader label="Validasi" field="validation" active={inputSort.field} direction={inputSort.direction} onSort={changeSort(setInputSort)}/><SortHeader label="Pembaruan" field="updated" active={inputSort.field} direction={inputSort.direction} onSort={changeSort(setInputSort)}/><th>Detail</th></tr></thead><tbody>{inputPage.rows.map(item=><tr key={item.id}><td>{item.item_name}</td><td>{item.category}</td><td>{getRegionById(item.region_id)?.name}</td><td>{formatInfrastructureValue(item.required_quantity,item.unit)}</td><td>{formatInfrastructureValue(item.available_quantity,item.unit)}</td><td>{formatInfrastructureValue(inputFulfillment(item)?.presentationPct??null,"%")}</td><td>{equipmentCategories.has(item.category)?formatInfrastructureValue(item.ready_quantity,item.unit):"Tidak relevan"}</td><td>{equipmentCategories.has(item.category)?formatInfrastructureValue(item.light_damage_quantity+item.heavy_damage_quantity,item.unit):"Tidak relevan"}</td><td>{validationLabel(item.validation_status)}</td><td>{dateId(item.updated_at)}</td><td><button onClick={()=>setDetail({kind:"input",item})} aria-label={`Detail sarana ${item.item_name}`}>Detail</button></td></tr>)}</tbody></table></div><Pagination page={inputPage.currentPage} totalPages={inputPage.totalPages} start={inputPage.start} end={inputPage.end} total={inputPage.total} onPage={setPage}/></>:<div className="table-empty" role="status">Tidak ada data sesuai filter.</div>}</section></>}
    </>)}
    <section className="monitoring-card monitoring-insight"><h2>Prioritas dan insight</h2><p>{tab==="irrigation"?"Prioritas ditentukan dari panjang kerusakan dan kecukupan air yang tercatat.":"Wilayah kekurangan ditentukan dari pemenuhan per kategori di bawah 100%."}</p><small>Insight berbasis aturan data tersedia, bukan AI generatif.</small></section>
    {detail&&<InfrastructureDetail detail={detail} onClose={()=>setDetail(null)}/>}
  </div>;
}
